// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GrasshopperVRBridge.IO
{
    public enum Accuracy : sbyte
    {
        Float = 0,
        Integer = 1,
        Even = 2,
        Odd = 3,
    }
}