// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GrasshopperVRBridge.IO
{

using global::System;
using global::FlatBuffers;

public struct BooleanToggle : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BooleanToggle GetRootAsBooleanToggle(ByteBuffer _bb) { return GetRootAsBooleanToggle(_bb, new BooleanToggle()); }
  public static BooleanToggle GetRootAsBooleanToggle(ByteBuffer _bb, BooleanToggle obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BooleanToggle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Guid { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetGuidBytes() { return __p.__vector_as_arraysegment(6); }
  public bool Value { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<BooleanToggle> CreateBooleanToggle(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset guidOffset = default(StringOffset),
      bool value = false) {
    builder.StartObject(3);
    BooleanToggle.AddGuid(builder, guidOffset);
    BooleanToggle.AddName(builder, nameOffset);
    BooleanToggle.AddValue(builder, value);
    return BooleanToggle.EndBooleanToggle(builder);
  }

  public static void StartBooleanToggle(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddGuid(FlatBufferBuilder builder, StringOffset guidOffset) { builder.AddOffset(1, guidOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(2, value, false); }
  public static Offset<BooleanToggle> EndBooleanToggle(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BooleanToggle>(o);
  }
};


}
