// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GrasshopperVRBridge.IO
{

using global::System;
using global::FlatBuffers;

public struct Components : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Components GetRootAsComponents(ByteBuffer _bb) { return GetRootAsComponents(_bb, new Components()); }
  public static Components GetRootAsComponents(ByteBuffer _bb, Components obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ComponentsBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "PARA"); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Components __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Component? ComponentsVector(int j) { int o = __p.__offset(4); return o != 0 ? (Component?)(new Component()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ComponentsVectorLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Components> CreateComponents(FlatBufferBuilder builder,
      VectorOffset componentsVectorOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Components.AddComponentsVector(builder, componentsVectorOffset);
    return Components.EndComponents(builder);
  }

  public static void StartComponents(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddComponentsVector(FlatBufferBuilder builder, VectorOffset componentsVectorOffset) { builder.AddOffset(0, componentsVectorOffset.Value, 0); }
  public static VectorOffset CreateComponentsVectorVector(FlatBufferBuilder builder, Offset<Component>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartComponentsVectorVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Components> EndComponents(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Components>(o);
  }
  public static void FinishComponentsBuffer(FlatBufferBuilder builder, Offset<Components> offset) { builder.Finish(offset.Value, "PARA"); }
};


}
