// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GrasshopperVRBridge.IO
{

public enum GenericComponent : byte
{
 NONE = 0,
 BooleanToggle = 1,
 NumberSlider = 2,
};


}
